export const ACTIONS = [
  { key: "view", label: "Ver" },
  { key: "create", label: "Crear" },
  { key: "edit", label: "Editar" },
  { key: "delete", label: "Eliminar" },
  { key: "viewall", label: "Ver todas" },
  { key: "asignar", label: "Asignar" },
  { key: "firm", label: "Firmar" },
];

export const SECTIONS = [
  { key: "home", label: "Home", actions: ["view"] },
  { key: "usuarios", label: "Usuarios", actions: ["view", "create", "edit", "delete"] },
  { key: "clientes", label: "Clientes", actions: ["view", "create", "edit", "delete"] },
  { key: "marcas", label: "Marcas", actions: ["view", "create", "edit", "delete"] },
  { key: "modelos", label: "Modelos", actions: ["view", "create", "edit", "delete"] },
  { key: "inventario", label: "Inventario", actions: ["view", "create", "edit", "delete"] },
  { key: "combomantenimiento", label: "Mantenimientos", actions: ["view", "create", "edit", "delete"] },
  { key: "precios", label: "Precios", actions: ["view", "create", "edit", "delete"] },
  { key: "inventariocarros", label: "Inventario carros", actions: ["view", "create", "edit", "delete"] },
  { key: "configuracion", label: "Configuración", actions: ["view", "create", "edit", "delete"] },
  { key: "citas", label: "Citas", actions: ["view", "create", "edit", "viewall"] },
  { key: "leadspv", label: "Leads PV", actions: ["view", "create", "edit", "asignar", "asignar"] },
  { key: "oportunidadespv", label: "Oportunidades PV", actions: ["view", "create", "edit", "asignar"] },
  { key: "agenda", label: "Agenda", actions: ["view", "create", "edit", "viewall"] },
  { key: "mensajes", label: "Mensajes", actions: ["view", "create", "edit", "delete"] },
  { key: "reportes", label: "Reportes", actions: ["view", "create", "edit", "delete"] },
  { key: "ordenes", label: "Órdenes", actions: ["view", "create", "edit", "delete"] },
  { key: "cotizacion", label: "Cotización", actions: ["view", "create", "edit", "delete"] },
  { key: "prospeccion", label: "Configuracion de Prospecciones", actions: ["view", "create", "edit", "delete"] },
  { key: "configagenda", label: "Configuración de Agenda", actions: ["view", "create", "edit", "delete"] },
  { key: "leads", label: "Leads", actions: ["view", "create", "edit", "asignar", "asignar","viewall"] },
  { key: "oportunidades", label: "Oportunidades", actions: ["view", "create", "edit", "asignar","viewall"] },
  { key: "configinventario", label: "Configuración de Inventario", actions: ["view", "create", "edit", "delete"] },
  { key: "configcotizacion", label: "Configuración de Cotización", actions: ["view", "create", "edit", "delete"] },
  { key: "reservas", label: "Reservas", actions: ["view", "create", "edit", "viewall"] },
];
